name: GCP

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE: fincash-backend
  REGION: us-central1
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/fincash-backend:latest
  DB_INSTANCE: ${{ secrets.GCP_PROJECT_ID }}:us-central1:bd-fincash-cl


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: hw-prod

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setup Cloud SDK & Docker
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Download SQL Auth Proxy v1
        run: "wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy"

      - name: Make the Cloud SQL Auth proxy executable
        run: "chmod +x cloud_sql_proxy"

      - name: Start the Cloud SQL proxy and run migrations
        run: |
          ./cloud_sql_proxy -instances=$DB_INSTANCE=tcp:5432 &
          sleep 3
          cd backend
          rm -rf node_modules package-lock.json
          npm install
          npx prisma migrate deploy
          
      - name: Build Docker image
        working-directory: ./backend
        run: docker build -t $IMAGE_NAME .

      - name: Push Docker image
        run: docker push $IMAGE_NAME

      - name: Deploy to Cloud Run
        id: deploy
        run: |
          gcloud run deploy ${{ env.SERVICE }} \
            --image ${{ env.IMAGE_NAME }} \
            --region ${{ env.REGION }} \
            --memory 512Mi \
            --min-instances 0 \
            --max-instances 1 \
            --platform managed \
            --port 5000 \
            --add-cloudsql-instances ${{ env.DB_INSTANCE }} \
            --allow-unauthenticated \
            --timeout=1000s

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
