name: GCP

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build, Migrate and Deploy
    runs-on: ubuntu-latest
    environment: hw-prod
    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/fincash-backend:latest
      # Configure a string de conexão apontando para o localhost na porta padrão do proxy
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      # Git checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Login to GCP (atualizado para ações mais recentes)
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Configura o gcloud
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      # gcloud configure docker
      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      # Baixa e configura o Cloud SQL Auth Proxy
      - name: Download Cloud SQL Auth Proxy
        run: |
          curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-proxies/v2.8.0/cloud-sql-proxy.linux.amd64
          chmod +x cloud-sql-proxy

      # Inicia o Proxy em background e executa as migrações do Prisma com segurança
      - name: Run Prisma Migrations
        working-directory: ./backend
        run: |
          ../cloud-sql-proxy fincashs:us-central1:bd-898990 --port=5432 &
          
          # Aguarda o proxy subir e roda as migrações
          sleep 3
          npx prisma migrate deploy

      # build image
      - name: Build Docker image
        working-directory: ./backend
        run: docker build -t $IMAGE_NAME .

      # push image to registry
      - name: Push Docker image
        run: docker push $IMAGE_NAME

      # deploy image (sem as migrações embutidas no container)
      - name: Deploy Docker image
        run: |
          gcloud run deploy fincash-backend \
            --image $IMAGE_NAME \
            --region us-central1 \
            --memory 512Mi \
            --min-instances 0 \
            --max-instances 1 \
            --platform managed \
            --port 5000 \
            --add-cloudsql-instances fincashs:us-central1:bd-898990 \
            --allow-unauthenticated \
            --timeout=300s
